// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MessagesColumns holds the columns for the "messages" table.
	MessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "time", Type: field.TypeTime},
		{Name: "local_id", Type: field.TypeInt64},
		{Name: "can_be_deleted", Type: field.TypeBool},
		{Name: "user_undelivered_messages", Type: field.TypeInt, Nullable: true},
	}
	// MessagesTable holds the schema information for the "messages" table.
	MessagesTable = &schema.Table{
		Name:       "messages",
		Columns:    MessagesColumns,
		PrimaryKey: []*schema.Column{MessagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "messages_users_undelivered_messages",
				Columns:    []*schema.Column{MessagesColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "bio", Type: field.TypeString, Nullable: true},
		{Name: "last_seen", Type: field.TypeTime, Nullable: true},
		{Name: "refresh_token_expiry", Type: field.TypeInt64, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserUnrecivedMessagesColumns holds the columns for the "user_unrecived_messages" table.
	UserUnrecivedMessagesColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt},
		{Name: "message_id", Type: field.TypeInt},
	}
	// UserUnrecivedMessagesTable holds the schema information for the "user_unrecived_messages" table.
	UserUnrecivedMessagesTable = &schema.Table{
		Name:       "user_unrecived_messages",
		Columns:    UserUnrecivedMessagesColumns,
		PrimaryKey: []*schema.Column{UserUnrecivedMessagesColumns[0], UserUnrecivedMessagesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_unrecived_messages_user_id",
				Columns:    []*schema.Column{UserUnrecivedMessagesColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_unrecived_messages_message_id",
				Columns:    []*schema.Column{UserUnrecivedMessagesColumns[1]},
				RefColumns: []*schema.Column{MessagesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MessagesTable,
		UsersTable,
		UserUnrecivedMessagesTable,
	}
)

func init() {
	MessagesTable.ForeignKeys[0].RefTable = UsersTable
	UserUnrecivedMessagesTable.ForeignKeys[0].RefTable = UsersTable
	UserUnrecivedMessagesTable.ForeignKeys[1].RefTable = MessagesTable
}
