// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldBio holds the string denoting the bio field in the database.
	FieldBio = "bio"
	// FieldLastSeen holds the string denoting the last_seen field in the database.
	FieldLastSeen = "last_seen"
	// FieldRefreshTokenExpiry holds the string denoting the refresh_token_expiry field in the database.
	FieldRefreshTokenExpiry = "refresh_token_expiry"
	// EdgeUnrecivedMessages holds the string denoting the unrecived_messages edge name in mutations.
	EdgeUnrecivedMessages = "unrecived_messages"
	// EdgeUndeliveredMessages holds the string denoting the undelivered_messages edge name in mutations.
	EdgeUndeliveredMessages = "undelivered_messages"
	// Table holds the table name of the user in the database.
	Table = "users"
	// UnrecivedMessagesTable is the table that holds the unrecived_messages relation/edge. The primary key declared below.
	UnrecivedMessagesTable = "user_unrecived_messages"
	// UnrecivedMessagesInverseTable is the table name for the Message entity.
	// It exists in this package in order to avoid circular dependency with the "message" package.
	UnrecivedMessagesInverseTable = "messages"
	// UndeliveredMessagesTable is the table that holds the undelivered_messages relation/edge.
	UndeliveredMessagesTable = "messages"
	// UndeliveredMessagesInverseTable is the table name for the Message entity.
	// It exists in this package in order to avoid circular dependency with the "message" package.
	UndeliveredMessagesInverseTable = "messages"
	// UndeliveredMessagesColumn is the table column denoting the undelivered_messages relation/edge.
	UndeliveredMessagesColumn = "user_undelivered_messages"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldName,
	FieldPasswordHash,
	FieldBio,
	FieldLastSeen,
	FieldRefreshTokenExpiry,
}

var (
	// UnrecivedMessagesPrimaryKey and UnrecivedMessagesColumn2 are the table columns denoting the
	// primary key for the unrecived_messages relation (M2M).
	UnrecivedMessagesPrimaryKey = []string{"user_id", "message_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	PasswordHashValidator func(string) error
)
